@startuml euphonic_context_with_api
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

HIDE_STEREOTYPE()

'Example of how to change colours
/'skinparam rectangle<<person>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $PERSON_BG_COLOR
    BorderColor #073B6F
}'/
skinparam ArrowFontSize 18
skinparam DefaultFontSize 18
skinparam dpi 600
skinparam rectangle<<file_system>> {
    StereotypeFontColor #000000
    FontColor #000000
    BackgroundColor #85BBF0
    BorderColor #78A8D8
}
!unquoted procedure System_File($alias, $label, $descr="", $sprite="")
rectangle "$getSystem($label, $descr, $sprite)" <<file_system>> as $alias
!endprocedure

Person(horace_user, "Horace User", "")
Person(abins_user, "Abins User", "")
Person(euphonic_cl_user, "Euphonic Command Line Tool User", "")
Person(euphonic_api_user, "Euphonic API User", "")

Boundary(euphonic, "Euphonic"){
    System(euphonic_api, "Python API", "Calculation and plotting of phonon bandstructures, DOS and neutron spectra from force constants")
    System(euphonic_cli, "Command Line Tools", "Quick plotting of bandstructures, DOS and neutron spectra")
}
System_Ext(horace, "Horace", "Visualisation, analysis and simulation of direct inelastic neutron scattering instrument data")
System_Ext(hor_eu_interface, "Horace-Euphonic-Interface", "Matlab add-on to allow use of Euphonic in Horace simulation functions")
Boundary(mantid, "Mantid"){
    System_Ext(abins, "Abins", "Mantid plugin for comparison of experimental and simulated indirect inelastic neutron scattering instrument data")
}
System_File(force_constants, "Force Constants File")
System_File(phonons, "Phonon Frequencies and Eigenvectors File")

AddRelTag("dashed", $lineStyle = DashedLine())

Rel_D(euphonic_api_user, euphonic_api, "Uses")
Rel_D(euphonic_cl_user, euphonic_cli, "Uses")
Rel_R(euphonic_cli, euphonic_api, "Uses")

Rel_D(horace_user, horace, "Uses")
Rel_D(horace_user, hor_eu_interface, "Uses")
Rel_R(horace, hor_eu_interface, "Gives experimental q-points")
Rel_L(hor_eu_interface, horace, "Returns structure factors and frequencies")
Rel_D(hor_eu_interface, euphonic_api, "Uses")

Rel_D(abins_user, mantid, "Uses")
Rel_L(abins, euphonic_api, "Uses")

Rel_U(force_constants, euphonic_api, "Is read by")
Rel_U(phonons, euphonic_api, "Is read by")

Lay_U(euphonic_api_user, horace)
Lay_U(euphonic_cl_user, horace)
Lay_D(hor_eu_interface, abins)

@enduml