@startuml ResScheme

skinparam class {
BackgroundColor White
ArrowColor Black
BorderColor Black
}

class OptFunction{
    - ResScheme scheme
    + get_scheme()
    + set_scheme()
}

class ResScheme{
    - bool has_effect = false
    + bool does_anything(){\n  return has_effect;\n}
    + {abstract} convolute()
}

class ResTobyfit{
    - bool has_effect = true
    - array mc_contributions
    - integer mc_points
    - struct refine_crystal
    - struct refine_tobyfit
    + convolute()
}

class ResRaytrace{
    - bool has_effect = true
    - ...
    + convolute()
}

OptFunction *-- ResScheme
ResScheme <|-- ResTobyfit
ResScheme <|-- ResRaytrace
@enduml
